### ISSUE TITLE
Rule designer?

### ISSUE THREAD

**Issue by dmenne** [gdvallance/production-openclinica-docker#1]
Thanks for having started a great project. I tried to integrate the [rule designer](https://community.openclinica.com/extension/openclinica-rule-designer-0) installed locally, but could not find any documentation how to install it.

**Comment by dmenne** [comment]
The war-file mentioned in 

https://us.v-cdn.net/5021087/uploads/FileUpload/9c/11c493a4ccbfd17600ad79193a1b5e.pdf

does no longer exist

**Comment by gdvallance** [comment]
Apologies for the delay in replying. 

I was not aware of the Rule Designer tool, even though notionally there is a button on my installation (that does not work). 

My OpenClinica experience is relatively limited and hitherto I have not used Rules. Consequently, adding the Rule Designer or getting it to work was not part of my mental roadmap.

I cannot find anything about installing it as well ... So either it is meant to work out-of-the-box and my container implementatation has broken it or there is an undocumented install process that needs to be discovered ...

Unfortunately, at the moment I don't have the time (or perhaps the skill yet) to fix it (if broken), or to discover and implement an installation based instructions to be discovered.

So I am going to close the issue. However, I will keep it in mind and see what can be done in due course.
